# Generated by Django 4.2 on 2023-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.SmallIntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.FloatField()),
                ('eaddr', models.TextField()),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ('-ename',),
            },
        ),
    ]
